Revise installation command for kurtosis-ethereum
The command written in the README doesn't exist.

```bash
mushow@MacBook-Pro ~ % claude skill install --name kurtosis-ethereum github.com/ethpandaops/ethereum-package/.claude/skills/kurtosis-ethereum
error: unknown option '--name'
```

Signed-off-by: 0xMushow <105550256+0xMushow@users.noreply.github.com>